# High-Performance Trading Backend Configuration

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  binary_websocket_enabled: true
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# Logging Configuration
logging:
  level: "info"          # debug, info, warn, error
  format: "text"         # text, json
  output: "stdout"       # stdout, stderr, file

# Database Configuration
database:
  mysql:
    host: "localhost"
    port: 3307
    database: "trading"
    username: "trading"
    password: "trading123"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: "5m"
  
  influx:
    url: "http://localhost:8086"
    token: "my-super-secret-auth-token"
    org: "trading-org"
    bucket: "trading"
    timeout: "30s"

# Cache Configuration (Redis)
cache:
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 100
    min_idle_conns: 10
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"

# Messaging Configuration (NATS)
messaging:
  nats:
    url: "nats://localhost:4222"
    max_reconnect: -1
    reconnect_wait: "1s"
    drain_timeout: "30s"

# Exchange Configuration
exchange:
  binance:
    stream_url: "wss://stream.binance.com:9443/stream"
    api_url: "https://api.binance.com"
  
  max_symbols_per_connection: 200
  reconnect_delay: "1s"
  max_reconnect_attempts: 10
  connection_timeout: "30s"
  ping_interval: "20s"

# Performance Configuration
performance:
  # Binary Protocol
  binary_batch_size: 50
  binary_batch_interval: "50ms"
  
  # WebSocket
  heartbeat_interval: "30s"
  max_message_size: 512
  write_buffer_size: 1024
  read_buffer_size: 1024
  
  # Price Processing
  price_buffer_size: 10000
  price_update_interval: "100ms"
  
  # Cache
  cache_ttl: "5m"
  cache_cleanup_interval: "10m"

# Features Configuration
features:
  enigma_enabled: true
  enigma_calculation_interval: "5s"
  
  tradingview_enabled: true
  tradingview_resolutions: ["1", "5", "15", "30", "60", "1D"]
  
  market_watch_enabled: true
  max_watchlist_symbols: 100

# Security Configuration
security:
  cors_enabled: true
  cors_origins: ["*"]
  cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  
  rate_limit_enabled: true
  rate_limit_requests: 1000
  rate_limit_window: "1m"

# Monitoring Configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_enabled: true